name: Build SpatialPulse

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build with MSBuild
        run: msbuild src\SpatialPulse.sln /p:Configuration=Release